[project]
name = "evo2-deepdive"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kaggle>=1.7.4.5",
    "torch>=2.7.0",
    "transformers>=4.51.3",
]
